# Build stage
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /naves
COPY pom.xml .
COPY src ./src
RUN mvn dependency:go-offline  # Descarga las dependencias sin compilar
RUN mvn clean package -DskipTests

# Run stage
FROM openjdk:17-jdk-alpine
WORKDIR /naves
COPY --from=build /naves/target/naves-1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]